/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package EjerciciosT7;

public class App {
    public static void main(String[] args) {
        
    /*Ejercicio 6: No, solo en C++, en Java se finaliza automáticamente al 
    ocupar las posiciones de memorias deseadas*/    
        
    /*
      //Ejercicio 7
    
        AlgoritmosOrdenacion a = new AlgoritmosOrdenacion();
        
        System.out.println("\nOrdenacion \"Burbuja\": \n");
    
        long inicio=System.nanoTime();
        a.burbuja(a.getV1());
        long fin=System.nanoTime();
        System.out.print("Duracion del metodo burbuja con el array v1: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        a.burbuja(a.getV2());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo burbuja con el array v2: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        a.burbuja(a.getV3());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo burbuja con el array v3: " + (fin-inicio) + " nanosegundos.\n\n\n");
        
        
        AlgoritmosOrdenacion b = new AlgoritmosOrdenacion();
        
        System.out.println("Ordenacion \"Insercion\": \n");
        
        inicio=System.nanoTime();
        b.insercion(b.getV1());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo insercion con el array v1: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        b.insercion(b.getV2());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo insercion con el array v2: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        b.insercion(b.getV3());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo insercion con el array v3: " + (fin-inicio) + " nanosegundos.\n\n\n");
        
        
        AlgoritmosOrdenacion c = new AlgoritmosOrdenacion();
        
        System.out.println("Ordenacion \"Seleccion\": \n");
        
        inicio=System.nanoTime();
        c.seleccion(c.getV1());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo seleccion con el array v1: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        c.seleccion(c.getV2());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo seleccion con el array v2: " + (fin-inicio) + " nanosegundos.\n");
        
        inicio=System.nanoTime();
        c.seleccion(c.getV3());
        fin=System.nanoTime();
        System.out.print("Duracion del metodo seleccion con el array v3: " + (fin-inicio) + " nanosegundos.\n");
    */
    
    /*    
      //Ejercicio 14     
      
        long tInicio, tFinal;
        HashSetESports a1 = new HashSetESports();
        HashSetESports a2 = new HashSetESports();
        LinkedHashSetESports b1 = new LinkedHashSetESports();
        LinkedHashSetESports b2 = new LinkedHashSetESports();
    
        tInicio = System.nanoTime();
        a2 = a1.ordenarEquipo();
        tFinal = System.nanoTime();
        System.out.println("Tiempo de ejecucion: " + (tFinal-tInicio));
    
        tInicio = System.nanoTime();
        b2 = b1.ordenarEquipo();
        tFinal = System.nanoTime();
        System.out.println("Tiempo de ejecucion: " + (tFinal-tInicio));
    */
    
    
    
    }
}
